### ISSUE TITLE
VoidCore.Finance.Financial as static class

### ISSUE THREAD

**Issue by johnwc** [void-type/VoidCore#77]
Any reason why we can't get the `VoidCore.Finance` classes converted into static classes with the methods being static methods? No need to create an object in memory to just run a method that is static by design already.

For applications that use this library throughout their app this would cut down on memory footprint.

I'll create a PR with the updates if you are okay with it. I'll keep the existing not static class for backward compatibility.

**Comment by void-type** [comment]
Hi John. I think that's a good idea and something I definitely thought about. This change would actually make it a drop-in replacement for the VB Financial library, which was it's original purpose.

I'm not sure how many other people use this library, but I'm willing to make a breaking change and bump the version number to keep the API clean.

I went ahead and made a PR #78 because I wanted to benchmark it. I think the compiler was already optimizing it away so I'm not seeing any performance gains. See tests/VoidCore.Benchmark/results.md

If this suits your needs I'll merge and release.

**Comment by johnwc** [comment]
I pulled dev branch and changed the benchmark to the following and changed the class back to non static for the single method test. These are the results. It shows what I am referring to for creating an object to call a method vs calling a method statically. It's not a speed thing, it's a using memory that doesn't need to be.

So, yes the updates in the PR look great!

|   Method | total |     Mean |    Error |   StdDev | Ratio | RatioSD |   Gen0 | Allocated | Alloc Ratio |
|--------- |------ |---------:|---------:|---------:|------:|--------:|-------:|----------:|------------:|
| Baseline |  1000 | 147.2 us |  1.68 us |  1.49 us |  1.00 |    0.00 | 1.7090 |   24024 B |        1.00 |
|   Static |  1000 | 149.6 us |  2.98 us |  3.88 us |  1.02 |    0.03 |      - |         - |        0.00 |
|          |       |          |          |          |       |         |        |           |             |
| Baseline |  2000 | 307.9 us |  5.92 us |  7.27 us |  1.00 |    0.00 | 3.4180 |   48024 B |        1.00 |
|   Static |  2000 | 314.4 us |  5.75 us | 10.52 us |  1.02 |    0.04 |      - |         - |        0.00 |
|          |       |          |          |          |       |         |        |           |             |
| Baseline |  4000 | 645.7 us | 12.53 us | 14.43 us |  1.00 |    0.00 | 6.8359 |   96025 B |       1.000 |
|   Static |  4000 | 609.8 us | 11.98 us | 14.27 us |  0.94 |    0.02 |      - |       1 B |       0.000 |



```
[MemoryDiagnoser()]
public class FinanceBenchmarks
{
    [Params(1000, 2000, 4000)]
    public int total { get; set; }

    [Benchmark(Baseline = true)]
    public void Baseline()
    {
        for (int i = 0; i <= total; i++)
            new Financial().PresentValue(0.035m, 362, 0, 482_000);
    }

    [Benchmark()]
    public void Static()
    {
        for (int i = 0; i <= total; i++)
            Financial.PresentValueStatic(0.035m, 362, 0, 482_000);
    }

}
```

**Comment by void-type** [comment]
Oops, I think I let benchmark overwrite my non-static results and I was still seeing allocations. I see what you mean.

Merged!

**Comment by void-type** [comment]
11.0.2 released
